[[language]]
name = "svelte"
auto-format = true
language-servers = ["svelteserver", "typos"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "typos"]

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
language-servers = [ "gopls","golangci-lint-lsp", "typos"]
# TODO: gopls needs utf-8 offsets?
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex"]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]

[language-server.gopls]
command = "gopls"

[language-server.typos]
command = "typos-lsp"

[language-server.ltex]
command = "ltex-ls"

[language-server.ltex.config.ltex.dictionary]
"en-US" = ["mine"]

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.gopls.config]
"formatting.gofumpt" = true

[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }

# [language.config.check]
# command = "clippy"

# [language.language-server]
# command = "rustup"
# args = ["run", "stable", "rust-analyzer"]

# [language.debugger]
# command = "codelldb"
# name = "codelldb"
# port-arg = "--port {}"
# transport = "tcp"

# [[language.debugger.templates]]
# name = "binary"
# request = "launch"

# [[language.debugger.templates.completion]]
# completion = "filename"
# name = "binary"

# [language.debugger.templates.args]
# program = "{0}"
# runInTerminal = true
